# Generated by Django 3.1.1 on 2020-10-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('origin', models.CharField(choices=[('Produção', 'Produção'), ('Homologação', 'Homologação'), ('Dev', 'Dev')], default='Produção', max_length=11, verbose_name='Origem')),
                ('level', models.CharField(choices=[('Debug', 'Debug'), ('Error', 'Error'), ('Warning', 'Warning')], default='Error', max_length=7, verbose_name='Nível')),
                ('events', models.IntegerField(verbose_name='Eventos')),
                ('archived', models.BooleanField(default=False, verbose_name='Arquivado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
