# Generated by Django 3.1.1 on 2020-11-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='origin',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
